# Generated by Django 5.2.1 on 2025-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='key',
            field=models.CharField(default='broke', max_length=200),
            preserve_default=False,
        ),
    ]
